[build]
  base = "/frontend"
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "/build"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"
NODE_VERSION = "18"
CI = "false"
